// Auto-generated by scripts/build-plugin-zip.mjs
export const PLUGIN_VERSION = '0.1.0'
export const ZIP_PATH = '/downloads/ccru-gematria-plugin.zip'
export const ZIP_SHA256 = '4eb8887a2d350b140af3efc0f61f280ba996c92663921234b27169dcb2a67dc6'
