// Auto-generated by scripts/build-plugin-zip.mjs
export const PLUGIN_VERSION = '0.1.0'
export const ZIP_PATH = '/downloads/ccru-gematria-plugin.zip'
export const ZIP_SHA256 = '455a4f70c103b39aaed8593bd6b0114ca6ab72d3a0357d1d9437abaa02fd4408'
